-- OPERADORES COMPARAÇÃO

SELECT * FROM CODFUNC WHERE DEPTO = ‘5’;
 SELECT * FROM CODFUNC WHERE FUNCAO = 'VENDEDOR'; 
 SELECT * FROM CODFUNC WHERE SALARIO <= 1700; 
 SELECT * FROM CODFUNC WHERE SALARIO > 1700 + 50;
 SELECT * FROM CODFUNC WHERE SALARIO > (1700 + 50);
 
 -- OPERADORES LÓGICOS
 
 SELECT * FROM CODFUNC WHERE (DEPTO = '3') AND (FUNCAO = 'PROGRAMADOR');
 SELECT * FROM CODFUNC WHERE (DEPTO = '3') OR (DEPTO = '5');
 SELECT * FROM CODFUNC WHERE NOT (FUNCAO = 'VENDEDOR');
 SELECT * FROM CODFUNC WHERE (DEPTO = '5') XOR (FUNCAO = 'PROGRAMADOR'); 

-- OPERADORES ADICIONAIS

ALTER TABLE CODFUNC ADD ID_DEPARTAMENTO SMALLINT; 
ALTER TABLE MORTO ADD FILHOS SMALLINT; 
ALTER TABLE MORTO ADD PAIS SMALLINT; 
ALTER TABLE CODFUNC ADD SAL SMALLINT; 

